#!/usr/bin/env bash
# This script prints "bad luck from china" on 4th iteration, "bad luck from japan" on the 9th iteration, and "bad luck from italy" on 17th iteration

n=1

while [ $n -le 20 ]
do
    echo $n
    case $n in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    n=$(( n + 1 ))
done
